/**
 * PM2 process definitions for the production VPS.
 *
 * This is the single source of truth for how each app is run under PM2.
 * The per-project Nx `deploy` targets simply build the app and then run:
 *
 *     pm2 startOrReload ecosystem.config.js --only <name> --update-env
 *
 * so deploys are idempotent (start if missing, reload if already running)
 * instead of the fragile `pm2 delete X || : && pm2 start X` dance.
 *
 * Why the Next/Nx apps are launched through `pnpm`:
 *   `node_modules/.bin/next` (and the other bins) are POSIX shell shims
 *   generated by pnpm. PM2's fork mode defaults to the Node interpreter and
 *   tries to parse those shims as JavaScript, which throws
 *   `SyntaxError: missing ) after argument list`. Going through `pnpm` gives
 *   PM2 a real Node entrypoint, and lets Nx resolve each app's custom
 *   `distDir` correctly (raw `next start` cannot with the withNx wrapper).
 */

const workspaceRoot = __dirname;

/** Base options shared by every managed process. */
const common = {
	cwd: workspaceRoot,
	autorestart: true,
	max_restarts: 10,
	restart_delay: 3000,
	// Give the process time to boot before PM2 considers it "online".
	min_uptime: 5000,
	time: true,
	env: {
		NODE_ENV: "production",
	},
};

/** Run an Nx target under PM2 through pnpm. */
function nxApp(name, target, args = []) {
	return {
		...common,
		name,
		script: "pnpm",
		args: ["nx", "run", target, ...args],
	};
}

module.exports = {
	apps: [
		nxApp("Caching-api", "caching-api:serve:production"),
		nxApp("Portfolio", "portfolio:serve-PROD", ["--port=4200"]),
		nxApp("HugoMeet", "hugomeet:serve:production", ["--port=3000"]),
		{
			...common,
			name: "HugoMeet-SS",
			script: "apps/hugomeet-SS/src/signallingServer.js",
		},
	],
};
